/* soapClient.c
   Generated by gSOAP 2.7.7 from posService.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.7 2015-03-24 06:29:58 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__posRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__posRequest *ns2__posRequest, struct ns2__posRequestResponse *ns2__posRequestResponse)
{	struct __ns1__posRequest soap_tmp___ns1__posRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.20.26:8800/A-Pay/services/posService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__posRequest.ns2__posRequest = ns2__posRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__posRequest(soap, &soap_tmp___ns1__posRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__posRequest(soap, &soap_tmp___ns1__posRequest, "-ns1:posRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__posRequest(soap, &soap_tmp___ns1__posRequest, "-ns1:posRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns2__posRequestResponse(soap, ns2__posRequestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__posRequestResponse(soap, ns2__posRequestResponse, "ns2:posRequestResponse", "ns2:posRequestResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__posUserRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__posUserRequest *ns2__posUserRequest, struct ns2__posUserRequestResponse *ns2__posUserRequestResponse)
{	struct __ns1__posUserRequest soap_tmp___ns1__posUserRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.20.26:8800/A-Pay/services/posService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__posUserRequest.ns2__posUserRequest = ns2__posUserRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__posUserRequest(soap, &soap_tmp___ns1__posUserRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__posUserRequest(soap, &soap_tmp___ns1__posUserRequest, "-ns1:posUserRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__posUserRequest(soap, &soap_tmp___ns1__posUserRequest, "-ns1:posUserRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_ns2__posUserRequestResponse(soap, ns2__posUserRequestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__posUserRequestResponse(soap, ns2__posUserRequestResponse, "ns2:posUserRequestResponse", "ns2:posUserRequestResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
