/* soapH.h
   Generated by gSOAP 2.7.7 from posService.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns1__posUserRequest
#define SOAP_TYPE___ns1__posUserRequest (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__posUserRequest(struct soap*, const struct __ns1__posUserRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__posUserRequest(struct soap*, struct __ns1__posUserRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__posUserRequest(struct soap*, const struct __ns1__posUserRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__posUserRequest(struct soap*, const char*, int, const struct __ns1__posUserRequest *, const char*);
SOAP_FMAC3 struct __ns1__posUserRequest * SOAP_FMAC4 soap_get___ns1__posUserRequest(struct soap*, struct __ns1__posUserRequest *, const char*, const char*);
SOAP_FMAC3 struct __ns1__posUserRequest * SOAP_FMAC4 soap_in___ns1__posUserRequest(struct soap*, const char*, struct __ns1__posUserRequest *, const char*);

#ifndef SOAP_TYPE___ns1__posRequest
#define SOAP_TYPE___ns1__posRequest (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__posRequest(struct soap*, const struct __ns1__posRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__posRequest(struct soap*, struct __ns1__posRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__posRequest(struct soap*, const struct __ns1__posRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__posRequest(struct soap*, const char*, int, const struct __ns1__posRequest *, const char*);
SOAP_FMAC3 struct __ns1__posRequest * SOAP_FMAC4 soap_get___ns1__posRequest(struct soap*, struct __ns1__posRequest *, const char*, const char*);
SOAP_FMAC3 struct __ns1__posRequest * SOAP_FMAC4 soap_in___ns1__posRequest(struct soap*, const char*, struct __ns1__posRequest *, const char*);

#ifndef SOAP_TYPE_ns2__posUserRequestResponse
#define SOAP_TYPE_ns2__posUserRequestResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__posUserRequestResponse(struct soap*, const struct ns2__posUserRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__posUserRequestResponse(struct soap*, struct ns2__posUserRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__posUserRequestResponse(struct soap*, const struct ns2__posUserRequestResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__posUserRequestResponse(struct soap*, const char*, int, const struct ns2__posUserRequestResponse *, const char*);
SOAP_FMAC3 struct ns2__posUserRequestResponse * SOAP_FMAC4 soap_get_ns2__posUserRequestResponse(struct soap*, struct ns2__posUserRequestResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__posUserRequestResponse * SOAP_FMAC4 soap_in_ns2__posUserRequestResponse(struct soap*, const char*, struct ns2__posUserRequestResponse *, const char*);

#ifndef SOAP_TYPE_ns2__userEntity
#define SOAP_TYPE_ns2__userEntity (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__userEntity(struct soap*, const struct ns2__userEntity *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__userEntity(struct soap*, struct ns2__userEntity *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__userEntity(struct soap*, const struct ns2__userEntity *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__userEntity(struct soap*, const char*, int, const struct ns2__userEntity *, const char*);
SOAP_FMAC3 struct ns2__userEntity * SOAP_FMAC4 soap_get_ns2__userEntity(struct soap*, struct ns2__userEntity *, const char*, const char*);
SOAP_FMAC3 struct ns2__userEntity * SOAP_FMAC4 soap_in_ns2__userEntity(struct soap*, const char*, struct ns2__userEntity *, const char*);

#ifndef SOAP_TYPE_ns2__posUserRequest
#define SOAP_TYPE_ns2__posUserRequest (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__posUserRequest(struct soap*, const struct ns2__posUserRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__posUserRequest(struct soap*, struct ns2__posUserRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__posUserRequest(struct soap*, const struct ns2__posUserRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__posUserRequest(struct soap*, const char*, int, const struct ns2__posUserRequest *, const char*);
SOAP_FMAC3 struct ns2__posUserRequest * SOAP_FMAC4 soap_get_ns2__posUserRequest(struct soap*, struct ns2__posUserRequest *, const char*, const char*);
SOAP_FMAC3 struct ns2__posUserRequest * SOAP_FMAC4 soap_in_ns2__posUserRequest(struct soap*, const char*, struct ns2__posUserRequest *, const char*);

#ifndef SOAP_TYPE_ns2__posRequestResponse
#define SOAP_TYPE_ns2__posRequestResponse (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__posRequestResponse(struct soap*, const struct ns2__posRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__posRequestResponse(struct soap*, struct ns2__posRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__posRequestResponse(struct soap*, const struct ns2__posRequestResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__posRequestResponse(struct soap*, const char*, int, const struct ns2__posRequestResponse *, const char*);
SOAP_FMAC3 struct ns2__posRequestResponse * SOAP_FMAC4 soap_get_ns2__posRequestResponse(struct soap*, struct ns2__posRequestResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__posRequestResponse * SOAP_FMAC4 soap_in_ns2__posRequestResponse(struct soap*, const char*, struct ns2__posRequestResponse *, const char*);

#ifndef SOAP_TYPE_ns2__posRequest
#define SOAP_TYPE_ns2__posRequest (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__posRequest(struct soap*, const struct ns2__posRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__posRequest(struct soap*, struct ns2__posRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__posRequest(struct soap*, const struct ns2__posRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__posRequest(struct soap*, const char*, int, const struct ns2__posRequest *, const char*);
SOAP_FMAC3 struct ns2__posRequest * SOAP_FMAC4 soap_get_ns2__posRequest(struct soap*, struct ns2__posRequest *, const char*, const char*);
SOAP_FMAC3 struct ns2__posRequest * SOAP_FMAC4 soap_in_ns2__posRequest(struct soap*, const char*, struct ns2__posRequest *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons2__posUserRequestResponse
#define SOAP_TYPE_PointerTons2__posUserRequestResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__posUserRequestResponse(struct soap*, struct ns2__posUserRequestResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__posUserRequestResponse(struct soap*, struct ns2__posUserRequestResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__posUserRequestResponse(struct soap*, const char *, int, struct ns2__posUserRequestResponse *const*, const char *);
SOAP_FMAC3 struct ns2__posUserRequestResponse ** SOAP_FMAC4 soap_get_PointerTons2__posUserRequestResponse(struct soap*, struct ns2__posUserRequestResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__posUserRequestResponse ** SOAP_FMAC4 soap_in_PointerTons2__posUserRequestResponse(struct soap*, const char*, struct ns2__posUserRequestResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__posUserRequest
#define SOAP_TYPE_PointerTons2__posUserRequest (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__posUserRequest(struct soap*, struct ns2__posUserRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__posUserRequest(struct soap*, struct ns2__posUserRequest *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__posUserRequest(struct soap*, const char *, int, struct ns2__posUserRequest *const*, const char *);
SOAP_FMAC3 struct ns2__posUserRequest ** SOAP_FMAC4 soap_get_PointerTons2__posUserRequest(struct soap*, struct ns2__posUserRequest **, const char*, const char*);
SOAP_FMAC3 struct ns2__posUserRequest ** SOAP_FMAC4 soap_in_PointerTons2__posUserRequest(struct soap*, const char*, struct ns2__posUserRequest **, const char*);

#ifndef SOAP_TYPE_PointerTons2__posRequestResponse
#define SOAP_TYPE_PointerTons2__posRequestResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__posRequestResponse(struct soap*, struct ns2__posRequestResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__posRequestResponse(struct soap*, struct ns2__posRequestResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__posRequestResponse(struct soap*, const char *, int, struct ns2__posRequestResponse *const*, const char *);
SOAP_FMAC3 struct ns2__posRequestResponse ** SOAP_FMAC4 soap_get_PointerTons2__posRequestResponse(struct soap*, struct ns2__posRequestResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__posRequestResponse ** SOAP_FMAC4 soap_in_PointerTons2__posRequestResponse(struct soap*, const char*, struct ns2__posRequestResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__posRequest
#define SOAP_TYPE_PointerTons2__posRequest (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__posRequest(struct soap*, struct ns2__posRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__posRequest(struct soap*, struct ns2__posRequest *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__posRequest(struct soap*, const char *, int, struct ns2__posRequest *const*, const char *);
SOAP_FMAC3 struct ns2__posRequest ** SOAP_FMAC4 soap_get_PointerTons2__posRequest(struct soap*, struct ns2__posRequest **, const char*, const char*);
SOAP_FMAC3 struct ns2__posRequest ** SOAP_FMAC4 soap_in_PointerTons2__posRequest(struct soap*, const char*, struct ns2__posRequest **, const char*);

#ifndef SOAP_TYPE_PointerTons2__userEntity
#define SOAP_TYPE_PointerTons2__userEntity (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__userEntity(struct soap*, struct ns2__userEntity *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__userEntity(struct soap*, struct ns2__userEntity *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__userEntity(struct soap*, const char *, int, struct ns2__userEntity *const*, const char *);
SOAP_FMAC3 struct ns2__userEntity ** SOAP_FMAC4 soap_get_PointerTons2__userEntity(struct soap*, struct ns2__userEntity **, const char*, const char*);
SOAP_FMAC3 struct ns2__userEntity ** SOAP_FMAC4 soap_in_PointerTons2__userEntity(struct soap*, const char*, struct ns2__userEntity **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
