#ifndef _DICTION_NUM2_H_
#define _DICTION_NUM2_H_

#define  MSGID                  0        /* 0号域消息类型                */
#define  BITMAP                 1        /* 1号域位图                    */
#define  ACCTNO                 2        /* 2号域主账号                  */
#define  PROCESSCODE            3        /* 3号域交易处理码              */
#define  AMT                    4        /* 4号域交易金额                */
#define  TXNUM                  5        /* 5号域保留域(消费次数)        */
#define  TRANSDATETIME          7        /* 7号域交易传输时间            */
#define  TRACENO                11       /* 11号域系统跟踪号             */
#define  TXTIME                 12       /* 交易时间                     */
#define  TXDATE                 13       /* 交易日期                     */
#define  EXPIRE                 14       /* 14号域卡有效期               */
#define  SETTLEDATE             15       /* 15号域清算日期               */
#define  MERTYPE                18       /* 18号域商户类型               */
#define  SERMODE                22       /* 22号域服务点输入方式码       */
#define  SERCODE                25       /* 25号域服务点条件码           */
#define  SERPINCODE             26       /* 26号域服务点PIN获取码        */
#define  FEE                    28       /* 28号域手续费                 */
#define  ACQUIRE                32       /* 32号域代理机构标识码         */
#define  ISSURE                 33       /* 33号域发送机构标识码         */
#define  TK2                    35       /* 35号域第二磁道数据           */
#define  TK3                    36       /* 36号域第三磁道数据           */
#define  REFNUM                 37       /* 37号域检索参考号             */
#define  AUTHNO                 38       /* 38号域授权标识应答码         */
#define  RETCODE                39       /* 39号域应答码                 */
#define  TERMINALID             41       /* 41号域终端标识码             */
#define  MERCHANTID             42       /* 42号域受卡方标识码           */
#define  MERCHANTADDER          43       /* 受卡方名称地址               */
#define  ADDITIONAL             44       /* 44号域附加响应数据           */
#define  FIELD46                46       /* 46域附件数据                 */
#define  ADDPRIVATE             48       /* 48号域附加数据               */
#define  CURRCODE               49       /* 49号域交易货币代码           */
#define  CURRSETTLECODE         50       /* 50号域清算币种               */
#define  PINDATA                52       /* 52号域个人标识码数据         */
#define  SECUINFO               53       /* 53号域安全控制信息           */
#define  BALANCE                54       /* 54号域实际余额               */
#define  FIELD57                57       /* 57号域自定义                 */
#define  FIELD60                60       /* 60号域自定义域               */
#define  FIELD61                61       /* 61号域自定义                 */
#define  FIELD62                62       /* 62号域自定义                 */
#define  FIELD63                63       /* 63号域自定义                 */
#define  SETTLECODE             66       /* 66号域清算代码               */
#define  NETMANAGECODE          70       /* 70号域网络管理信息码         */
#define  CREDITNUM              74       /* 74号域贷记笔数               */
#define  CREDITNUMREVER         75       /* 75号域冲正贷记笔数           */
#define  DEBITNUM               76       /* 76号域借记笔数               */
#define  DEBITNUMREVER          77       /* 77号域冲正借记笔数           */
#define  CREDITAMT              86       /* 86号域贷记金额               */
#define  CREDITAMTREVER         87       /* 87号域冲正贷记金额           */
#define  DEBITAMT               88       /* 88号域借记金额               */
#define  DEBITAMTREVER          89       /* 89号域冲正借记金额           */
#define  ORIGINALDATA           90       /* 90号域原始数据元             */
#define  SETTLEORGCODE          99       /* 99号域清算机构代码           */
#define  RECV_INST_ID_CODE      100      /* 100接收机构标识码            */
#define  ACCIDEN1               102      /* 102号域账户标识1             */
#define  ACCIDEN2               103      /* 103号域账户标识2             */
#define  TRANSEXPLAIN           104      /* 104号域交易说明              */
#define  FIELD121               121      /* 121号域受理方保留            */
#define  FIELD122               122      /* 122号域受理方保留3           */
#define  FIELD123               123      /* 123号域发卡方保留1           */
#define  FIELD124               124      /* 124号域受理方保留4           */
#define  FIELD125               125      /* 125号域受理方保留5           */
#define  FIELD126               126      /* 126号域发卡方保留2           */
#define  MAC128                 128      /* 128号域消息鉴别码            */

#endif
